# Generated by Django 5.2.12 on 2026-08-21 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import simmate.database.core.archive
from simmate.apps.rdkit.utils import get_rdkit_ext_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aflow", "0002_aflowprototype_is_invalid_structure_and_more"),
        ("bcpc", "0002_initial"),
        ("cas_registry", "0003_remove_casregistrymolecule_physical_state_and_more"),
        ("chembl", "0005_remove_chemblassayresult_source_and_more"),
        ("chemspace", "0002_initial"),
        ("cod", "0003_alter_codstructure_id"),
        ("core", "0007_feedback"),
        ("emolecules", "0002_initial"),
        ("enamine", "0002_initial"),
        ("inventory_management", "0001_setup"),
        ("jarvis", "0002_jarvisstructure_is_invalid_structure"),
        ("materials_project", "0003_matprojstructure_is_invalid_structure"),
        ("oqmd", "0004_remove_oqmdstructure_formation_energy_and_more"),
        ("pdb", "0003_rename_type_pdbligand_monomer_type_and_more"),
        ("ppdb", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mixture",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "mixture_type",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "common_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("synonyms", models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                "db_table": "inventory_management__mixtures",
            },
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.CreateModel(
            name="Molecule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("molecule", models.TextField(blank=True, null=True)),
                ("molecule_original", models.TextField(blank=True, null=True)),
                ("is_3d", models.BooleanField(blank=True, null=True)),
                ("smiles", models.TextField(blank=True, null=True)),
                ("inchi", models.TextField(blank=True, null=True)),
                (
                    "inchi_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True
                    ),
                ),
                ("num_atoms", models.IntegerField(blank=True, null=True)),
                ("num_stereocenters", models.IntegerField(blank=True, null=True)),
                ("num_rings", models.IntegerField(blank=True, null=True)),
                ("num_h_acceptors", models.IntegerField(blank=True, null=True)),
                ("num_h_donors", models.IntegerField(blank=True, null=True)),
                ("molecular_weight", models.FloatField(blank=True, null=True)),
                ("molecular_weight_exact", models.FloatField(blank=True, null=True)),
                ("functional_groups", models.JSONField(blank=True, null=True)),
                ("log_p_rdkit", models.FloatField(blank=True, null=True)),
                ("tpsa_rdkit", models.FloatField(blank=True, null=True)),
                ("synthetic_accessibility", models.FloatField(blank=True, null=True)),
                *get_rdkit_ext_fields(),
            ],
            options={
                "db_table": "inventory_management__molecules",
            },
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("is_mixture", models.BooleanField(blank=True, null=True)),
                ("batch_number", models.IntegerField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("purity", models.FloatField(blank=True, null=True)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                ("supplier", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "supplier_catalog_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("num_containers", models.IntegerField(blank=True, null=True)),
                (
                    "total_initial_amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "total_current_amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("amount_units", models.CharField(blank=True, max_length=5, null=True)),
                ("is_depleted", models.BooleanField(blank=True, null=True)),
                (
                    "mixture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="inventory_management.mixture",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_management__batches",
            },
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "temperature_celsius",
                    models.IntegerField(blank=True, default=20, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parent_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_locations",
                        to="inventory_management.storagelocation",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_management__storage_locations",
            },
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.CreateModel(
            name="Container",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("barcode", models.CharField(blank=True, max_length=100, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "initial_amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("amount_units", models.CharField(blank=True, max_length=5, null=True)),
                ("is_depleted", models.BooleanField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="containers",
                        to="inventory_management.batch",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="containers",
                        to="inventory_management.storagelocation",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_management__containers",
            },
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("structure", models.TextField(blank=True, null=True)),
                ("nsites", models.IntegerField(blank=True, null=True)),
                ("nelements", models.IntegerField(blank=True, null=True)),
                ("elements", models.JSONField(blank=True, null=True)),
                (
                    "chemical_system",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("is_invalid_structure", models.BooleanField(blank=True, null=True)),
                ("density", models.FloatField(blank=True, null=True)),
                ("density_atomic", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("volume_molar", models.FloatField(blank=True, null=True)),
                (
                    "formula_full",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "formula_reduced",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "formula_anonymous",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "spacegroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.spacegroup",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_management__structures",
            },
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.CreateModel(
            name="Substance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                (
                    "substance_type",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_theoretical",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_delisted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_private",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_unknown",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "common_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("iupac_name", models.TextField(blank=True, null=True)),
                ("synonyms", models.JSONField(blank=True, default=list, null=True)),
                (
                    "is_primary",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_metastable",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "has_stereochem",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("stereochem_type", models.JSONField(blank=True, null=True)),
                (
                    "stereochem_key",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("pubchem", models.CharField(blank=True, max_length=20, null=True)),
                ("extra_metadata", models.JSONField(blank=True, null=True)),
                (
                    "aflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="aflow.aflowstructure",
                    ),
                ),
                (
                    "bcpc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="bcpc.bcpcisopesticide",
                    ),
                ),
                (
                    "cas_registry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="cas_registry.casregistrymolecule",
                    ),
                ),
                (
                    "chembl",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="chembl.chemblmolecule",
                    ),
                ),
                (
                    "chemspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="chemspace.chemspacefreedomspacemolecule",
                    ),
                ),
                (
                    "cod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="cod.codstructure",
                    ),
                ),
                (
                    "emolecules",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="emolecules.emoleculesmolecule",
                    ),
                ),
                (
                    "enamine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="enamine.enaminerealmolecule",
                    ),
                ),
                (
                    "jarvis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="jarvis.jarvisstructure",
                    ),
                ),
                (
                    "materials_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="materials_project.matprojstructure",
                    ),
                ),
                (
                    "molecule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="inventory_management.molecule",
                    ),
                ),
                (
                    "oqmd",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="oqmd.oqmdstructure",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="inventory_management.substance",
                    ),
                ),
                (
                    "pdb",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="pdb.pdbligand",
                    ),
                ),
                (
                    "ppdb",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="ppdb.ppdbmolecule",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registered_substances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substances",
                        to="inventory_management.structure",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_management__substances",
            },
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.AddField(
            model_name="mixture",
            name="substances",
            field=models.ManyToManyField(
                blank=True,
                db_table="inventory_management__mixture_components",
                related_name="mixtures",
                to="inventory_management.substance",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="substance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="inventory_management.substance",
            ),
        ),
        migrations.CreateModel(
            name="UsageLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "amount_removed",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="inventory_management.container",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_management__usage_logs",
            },
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
    ]
