# Generated by Django 5.2.17 on 2026-10-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mixture",
            name="id_prefix",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="mixture",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
