# Generated by Django 4.2.7 on 2026-02-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory_management",
            "0002_substance_extra_metadata_substance_is_delisted_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="mixture",
            old_name="mixture_type_type",
            new_name="mixture_type",
        ),
    ]
