# Generated by Django 5.2.11 on 2026-03-28 02:44

import django.db.models.deletion
from django.db import migrations, models

import simmate.database.core.archive


class Migration(migrations.Migration):

    dependencies = [
        ("aflow", "0002_aflowprototype_is_invalid_structure_and_more"),
        ("bcpc", "0002_initial"),
        ("cas_registry", "0003_remove_casregistrymolecule_physical_state_and_more"),
        ("chembl", "0005_remove_chemblassayresult_source_and_more"),
        ("chemspace", "0002_initial"),
        ("cod", "0003_alter_codstructure_id"),
        ("core", "0007_feedback"),
        ("emolecules", "0002_initial"),
        ("enamine", "0002_initial"),
        ("inventory_management", "0003_rename_mixture_type_type_mixture_mixture_type"),
        ("jarvis", "0002_jarvisstructure_is_invalid_structure"),
        ("materials_project", "0003_matprojstructure_is_invalid_structure"),
        ("oqmd", "0003_alter_oqmdstructure_id"),
        ("pdb", "0002_initial"),
        ("ppdb", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Molecule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("molecule", models.TextField(blank=True, null=True)),
                ("molecule_original", models.TextField(blank=True, null=True)),
                ("is_3d", models.BooleanField(blank=True, null=True)),
                ("smiles", models.TextField(blank=True, null=True)),
                ("inchi", models.TextField(blank=True, null=True)),
                (
                    "inchi_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True
                    ),
                ),
                ("num_atoms", models.IntegerField(blank=True, null=True)),
                ("num_stereocenters", models.IntegerField(blank=True, null=True)),
                ("num_rings", models.IntegerField(blank=True, null=True)),
                ("num_h_acceptors", models.IntegerField(blank=True, null=True)),
                ("num_h_donors", models.IntegerField(blank=True, null=True)),
                ("molecular_weight", models.FloatField(blank=True, null=True)),
                ("molecular_weight_exact", models.FloatField(blank=True, null=True)),
                ("functional_groups", models.JSONField(blank=True, null=True)),
                ("log_p_rdkit", models.FloatField(blank=True, null=True)),
                ("tpsa_rdkit", models.FloatField(blank=True, null=True)),
                ("synthetic_accessibility", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "inventory_management__molecules",
            },
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.RemoveField(
            model_name="substance",
            name="cas_number",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="pubchem_cid",
        ),
        migrations.AddField(
            model_name="substance",
            name="cas_registry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="cas_registry.casregistrymolecule",
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="has_stereochem",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="is_metastable",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="is_primary",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="inventory_management.substance",
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="pubchem",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="stereochem_key",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="stereochem_type",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="substance",
            name="aflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="aflow.aflowstructure",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="bcpc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="bcpc.bcpcisopesticide",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="chembl",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="chembl.chemblmolecule",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="chemspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="chemspace.chemspacefreedomspacemolecule",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="cod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="cod.codstructure",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="emolecules",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="emolecules.emoleculesmolecule",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="enamine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="enamine.enaminerealmolecule",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="jarvis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="jarvis.jarvisstructure",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="materials_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="materials_project.matprojstructure",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="oqmd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="oqmd.oqmdstructure",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="pdb",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="pdb.pdbligand",
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="ppdb",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="ppdb.ppdbmolecule",
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="molecule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="inventory_management.molecule",
            ),
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("structure", models.TextField(blank=True, null=True)),
                ("nsites", models.IntegerField(blank=True, null=True)),
                ("nelements", models.IntegerField(blank=True, null=True)),
                ("elements", models.JSONField(blank=True, null=True)),
                (
                    "chemical_system",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("is_invalid_structure", models.BooleanField(blank=True, null=True)),
                ("density", models.FloatField(blank=True, null=True)),
                ("density_atomic", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("volume_molar", models.FloatField(blank=True, null=True)),
                (
                    "formula_full",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "formula_reduced",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "formula_anonymous",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "spacegroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.spacegroup",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_management__structures",
            },
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.AddField(
            model_name="substance",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="inventory_management.structure",
            ),
        ),
    ]
