# Generated by Django 5.2.17 on 2026-10-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0003_mixture_id_prefix_alter_mixture_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="substance",
            name="check_digit",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
