# Generated by Django 5.2.17 on 2026-10-03 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0004_substance_check_digit"),
        ("project_management", "0002_remove_transaction_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="usagelog",
            old_name="container",
            new_name="source_container",
        ),
        migrations.AddField(
            model_name="batch",
            name="appearance",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="inventory_management/batches/"
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="parent_batches",
            field=models.ManyToManyField(
                blank=True,
                db_table="inventory_management__batch_lineage",
                related_name="child_batches",
                to="inventory_management.batch",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="supplied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplied_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="container_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="container",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="inventory_management/containers/"
            ),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="extra_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storagelocation",
            name="storage_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                db_table="inventory_management__substance_projects",
                related_name="substances",
                to="project_management.project",
            ),
        ),
        migrations.AddField(
            model_name="usagelog",
            name="destination_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_usage_logs",
                to="inventory_management.batch",
            ),
        ),
    ]
