# Generated by Django 5.2.14 on 2026-10-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory_management",
            "0005_rename_container_usagelog_source_container_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="total_current_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="total_initial_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="current_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="initial_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usagelog",
            name="amount_removed",
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
    ]
