apiVersion: v2
name: simmate
version: 0.0.0
description: Simmate is a full-stack framework for chemistry research.
type: application
home: https://simmate.org/
sources:
  - https://github.com/jacksund/simmate
maintainers:
  - name: Jack Sundberg
    email: jacksundberg123@gmail.com
    url: https://jacksund.github.io/
