platform: k3s

service_account:
  enabled: false

nginx:
  hostname: simmate.example.com
  resources:
    requests:
      memory: 1Gi
      cpu: 0.25
      ephemeral: 100M
    limits:
      memory: 2Gi
      cpu: 1
      ephemeral: 500M

gunicorn:
  access_mode: ReadWriteOnce
  storage_class_name: simmate-efs-sc
  storage: 1Gi
  resources:
    requests:
      memory: 6Gi
      cpu: 0.5
      ephemeral: 1Gi
    limits:
      memory: 8Gi
      cpu: 1
      ephemeral: 2Gi

scheduler:
  resources:
    requests:
      memory: 2Gi
      cpu: 0.5
      ephemeral: 1Gi
    limits:
      memory: 4Gi
      cpu: 1
      ephemeral: 2Gi

postgres:
  password: example_password_123
  storage: 20Gi
  memory:
    request: 8Gi
    limit: 12Gi
  cpu:
    request: 1
    limit: 1
  ephemeral:
    request: 1Gi
    limit: 2Gi

simmate:
  postgres_rdkit_extension: true
  database:
    engine: django.db.backends.postgresql
    host: simmate-postgres-service
    name: simmate_dev
    user: postgres
    password: example_password_123
    port: 5432
  workers:
    replicas: 0
    access_mode: ReadWriteOnce
    storage_class_name: simmate-efs-sc
    storage: 20Gi
    resources:
      requests:
        memory: 2Gi
        cpu: 1
        ephemeral: 1Gi
      limits:
        memory: 4Gi
        cpu: 1
        ephemeral: 2Gi
