# Generated by Django 3.2.5 on 2021-09-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('third_parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AflowPrototype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_string', models.TextField()),
                ('nsites', models.IntegerField()),
                ('nelements', models.IntegerField()),
                ('chemical_system', models.CharField(max_length=25)),
                ('density', models.FloatField()),
                ('molar_volume', models.FloatField()),
                ('formula_full', models.CharField(max_length=50)),
                ('formula_reduced', models.CharField(max_length=50)),
                ('formula_anonymous', models.CharField(max_length=50)),
                ('mineral_name', models.CharField(blank=True, max_length=75, null=True)),
                ('aflow_id', models.CharField(max_length=30)),
                ('pearson_symbol', models.CharField(max_length=6)),
                ('strukturbericht', models.CharField(max_length=6)),
                ('nsites_wyckoff', models.IntegerField()),
                ('spacegroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='third_parties.spacegroup')),
            ],
        ),
    ]
