# Generated by Django 5.2.11 on 2026-03-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oqmd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oqmdstructure",
            name="is_invalid_structure",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
