# Generated by Django 5.2.11 on 2026-03-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oqmd", "0002_oqmdstructure_is_invalid_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oqmdstructure",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
