# Generated by Django 5.2.11 on 2026-03-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oqmd", "0003_alter_oqmdstructure_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oqmdstructure",
            name="formation_energy",
        ),
        migrations.AddField(
            model_name="oqmdstructure",
            name="energy_per_atom",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
