apiVersion: v1
kind: Secret
metadata:
  name: simmate-service-account-token
  namespace: simmate
  annotations:
    kubernetes.io/service-account.name: "simmate-service-account"
type: kubernetes.io/service-account-token
