apiVersion: apps/v1
kind: Deployment
metadata:
  name: simmate-scheduler-deployment
  labels:
    app: simmate-scheduler
spec:
  selector:
    matchLabels:
      app: simmate-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: simmate-scheduler
        # bug-fix: https://stackoverflow.com/questions/46336852/
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: simmate-scheduler
          image: simmate/simmate-gunicorn:latest
          command: ["simmate", "compute", "start-schedules"]
          env:
            {{- include "simmate.env_config" . | indent 12 }}
          resources:
            requests:
              memory: "2Gi"
              cpu: "0.5"
              ephemeral-storage: "1Gi"
            limits:
              memory: "4Gi"
              cpu: "1"
              ephemeral-storage: "2Gi"
