apiVersion: apps/v1
kind: Deployment
metadata:
  name: simmate-scheduler-deployment
  labels:
    app: simmate-scheduler
spec:
  selector:
    matchLabels:
      app: simmate-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: simmate-scheduler
        # bug-fix: https://stackoverflow.com/questions/46336852/
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: simmate-scheduler
          image: jacksund/simmate:latest
          command: ["simmate", "compute", "start-schedules"]
          env:
            {{- include "simmate.env_config" . | indent 12 }}
          resources:
            requests:
              memory: {{ .Values.scheduler.resources.requests.memory }}
              cpu: {{ .Values.scheduler.resources.requests.cpu }}
              ephemeral-storage: {{ .Values.scheduler.resources.requests.ephemeral }}
            limits:
              memory: {{ .Values.scheduler.resources.limits.memory }}
              cpu: {{ .Values.scheduler.resources.limits.cpu }}
              ephemeral-storage: {{ .Values.scheduler.resources.limits.ephemeral }}
