# Generated by Django 3.2.5 on 2021-09-01 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('third_parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MITRelaxation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefect_flow_run_name', models.CharField(blank=True, max_length=50, null=True)),
                ('prefect_flow_run_id', models.CharField(blank=True, max_length=50, null=True)),
                ('prefect_flow_run_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrections', models.TextField(blank=True, null=True)),
                ('band_gap', models.FloatField(blank=True, null=True)),
                ('is_gap_direct', models.BooleanField(blank=True, null=True)),
                ('energy_fermi', models.FloatField(blank=True, null=True)),
                ('conduction_band_minimum', models.FloatField(blank=True, null=True)),
                ('valence_band_maximum', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MITRelaxationStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_string', models.TextField()),
                ('nsites', models.IntegerField()),
                ('nelements', models.IntegerField()),
                ('chemical_system', models.CharField(max_length=25)),
                ('density', models.FloatField()),
                ('molar_volume', models.FloatField()),
                ('formula_full', models.CharField(max_length=50)),
                ('formula_reduced', models.CharField(max_length=50)),
                ('formula_anonymous', models.CharField(max_length=50)),
                ('ionic_step_number', models.IntegerField()),
                ('energy', models.FloatField(blank=True, null=True)),
                ('site_forces', models.JSONField(blank=True, null=True)),
                ('lattice_stress', models.JSONField(blank=True, null=True)),
                ('relaxation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='local_calculations.mitrelaxation')),
                ('spacegroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='third_parties.spacegroup')),
            ],
        ),
        migrations.AddField(
            model_name='mitrelaxation',
            name='structure_final',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relaxations_as_final', to='local_calculations.mitrelaxationstructure'),
        ),
        migrations.AddField(
            model_name='mitrelaxation',
            name='structure_start',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relaxations_as_start', to='local_calculations.mitrelaxationstructure'),
        ),
    ]
