# Generated by Django 3.2.6 on 2021-08-15 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('third_parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MITRelaxationInitialStructure',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('structure_string', models.TextField()),
                ('nsites', models.IntegerField()),
                ('nelements', models.IntegerField()),
                ('chemical_system', models.CharField(max_length=25)),
                ('density', models.FloatField()),
                ('molar_volume', models.FloatField()),
                ('formula_full', models.CharField(max_length=50)),
                ('formula_reduced', models.CharField(max_length=50)),
                ('formula_anonymous', models.CharField(max_length=50)),
                ('spacegroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='third_parties.spacegroup')),
            ],
        ),
        migrations.CreateModel(
            name='MITRelaxationFinalStructure',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('structure_string', models.TextField()),
                ('nsites', models.IntegerField()),
                ('nelements', models.IntegerField()),
                ('chemical_system', models.CharField(max_length=25)),
                ('density', models.FloatField()),
                ('molar_volume', models.FloatField()),
                ('formula_full', models.CharField(max_length=50)),
                ('formula_reduced', models.CharField(max_length=50)),
                ('formula_anonymous', models.CharField(max_length=50)),
                ('spacegroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='third_parties.spacegroup')),
            ],
        ),
        migrations.CreateModel(
            name='MITRelaxation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefect_flow_run_name', models.CharField(blank=True, max_length=50, null=True)),
                ('prefect_flow_run_id', models.CharField(blank=True, max_length=50, null=True)),
                ('prefect_flow_run_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrections', models.TextField(blank=True, null=True)),
                ('final_energy', models.FloatField(blank=True, null=True)),
                ('structure_final', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='local_calculations.mitrelaxationfinalstructure')),
                ('structure_initial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='local_calculations.mitrelaxationinitialstructure')),
            ],
        ),
    ]
