apiVersion: apps/v1
kind: Deployment
metadata:
  name: simmate-gunicorn-deployment
  labels:
    app: simmate-gunicorn
spec:
  selector:
    matchLabels:
      app: simmate-gunicorn
  replicas: 1
  template:
    metadata:
      labels:
        app: simmate-gunicorn
        # bug-fix: https://stackoverflow.com/questions/46336852/
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: simmate-gunicorn
          image: jacksund/simmate:{{ .Values.version }}
          imagePullPolicy: Always
          env:
            {{- include "simmate.env_config" . | indent 12 }}
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /staticfiles
              name: simmate-gunicorn-staticfiles
          resources:
            requests:
              memory: {{ .Values.gunicorn.memory.request }}
              cpu: {{ .Values.gunicorn.cpu.request }}
              ephemeral-storage: {{ .Values.gunicorn.ephemeral.request }}
            limits:
              memory: {{ .Values.gunicorn.memory.limit }}
              cpu: {{ .Values.gunicorn.cpu.limit }}
              ephemeral-storage: {{ .Values.gunicorn.ephemeral.limit }}
      volumes:
        - name: simmate-gunicorn-staticfiles
          persistentVolumeClaim:
            claimName: simmate-gunicorn-staticfiles