apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simmate-gunicorn-staticfiles
spec:
  accessModes:
    - {{ .Values.gunicorn.access_mode }}  # bc static files are shared with nginx deployment
  {{- if and (eq .Values.gunicorn.access_mode "ReadWriteMany") .Values.gunicorn.storage_class_name }}
  storageClassName: {{ .Values.gunicorn.storage_class_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.gunicorn.storage }}