# Generated by Django 5.2.14 on 2026-05-15 20:00

import django.db.models.deletion
import simmate.database.core.archive
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0007_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Baderkit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_time", models.FloatField(blank=True, null=True)),
                ("queue_time", models.FloatField(blank=True, null=True)),
                (
                    "workflow_name",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "workflow_version",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "computer_system",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                ("directory", models.CharField(blank=True, max_length=250, null=True)),
                ("run_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
                ("corrections", models.JSONField(blank=True, null=True)),
                ("source", models.JSONField(blank=True, null=True)),
                ("structure", models.TextField(blank=True, null=True)),
                ("nsites", models.IntegerField(blank=True, null=True)),
                ("nelements", models.IntegerField(blank=True, null=True)),
                ("elements", models.JSONField(blank=True, null=True)),
                (
                    "chemical_system",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("is_invalid_structure", models.BooleanField(blank=True, null=True)),
                ("density", models.FloatField(blank=True, null=True)),
                ("density_atomic", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("volume_molar", models.FloatField(blank=True, null=True)),
                (
                    "formula_full",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "formula_reduced",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "formula_anonymous",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("method_kwargs", models.JSONField(blank=True, null=True)),
                ("spin_system", models.CharField(blank=True, max_length=75, null=True)),
                ("species", models.JSONField(blank=True, null=True)),
                ("valence_counts", models.JSONField(blank=True, null=True)),
                ("vacuum_charge", models.FloatField(blank=True, null=True)),
                ("vacuum_volume", models.FloatField(blank=True, null=True)),
                (
                    "spacegroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.spacegroup",
                    ),
                ),
            ],
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.CreateModel(
            name="Bader",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("method_kwargs", models.JSONField(blank=True, null=True)),
                ("oxidation_states", models.JSONField(blank=True, null=True)),
                ("atom_charges", models.JSONField(blank=True, null=True)),
                ("atom_volumes", models.JSONField(blank=True, null=True)),
                ("atom_min_surface_distances", models.JSONField(blank=True, null=True)),
                ("atom_avg_surface_distances", models.JSONField(blank=True, null=True)),
                ("maxima_frac", models.JSONField(blank=True, null=True)),
                ("maxima_charge_values", models.JSONField(blank=True, null=True)),
                ("maxima_ref_values", models.JSONField(blank=True, null=True)),
                ("basin_charges", models.JSONField(blank=True, null=True)),
                ("basin_volumes", models.JSONField(blank=True, null=True)),
                (
                    "basin_min_surface_distances",
                    models.JSONField(blank=True, null=True),
                ),
                (
                    "basin_avg_surface_distances",
                    models.JSONField(blank=True, null=True),
                ),
                ("basin_atoms", models.JSONField(blank=True, null=True)),
                ("basin_atom_dists", models.JSONField(blank=True, null=True)),
                ("total_electron_number", models.FloatField(blank=True, null=True)),
                (
                    "baderkit_calculation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="baderkit.baderkit",
                    ),
                ),
            ],
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.CreateModel(
            name="Badelf",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("method_kwargs", models.JSONField(blank=True, null=True)),
                ("oxidation_states", models.JSONField(blank=True, null=True)),
                ("nna_structure", models.JSONField(blank=True, null=True)),
                ("atom_charges", models.JSONField(blank=True, null=True)),
                ("atom_volumes", models.JSONField(blank=True, null=True)),
                ("min_surface_distances", models.JSONField(blank=True, null=True)),
                ("avg_surface_distances", models.JSONField(blank=True, null=True)),
                ("maxima_elf_values", models.JSONField(blank=True, null=True)),
                ("nna_formula", models.CharField(blank=True, max_length=25, null=True)),
                ("nnas_per_formula", models.FloatField(blank=True, null=True)),
                ("nnas_per_reduced_formula", models.FloatField(blank=True, null=True)),
                ("num_nnas", models.IntegerField(blank=True, null=True)),
                ("nna_dimensionality", models.IntegerField(blank=True, null=True)),
                ("all_nna_dims", models.JSONField(blank=True, null=True)),
                ("all_nna_dim_cutoffs", models.JSONField(blank=True, null=True)),
                ("total_electron_number", models.FloatField(blank=True, null=True)),
                (
                    "baderkit_calculation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="baderkit.baderkit",
                    ),
                ),
            ],
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.CreateModel(
            name="ElfLabeler",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("method_kwargs", models.JSONField(blank=True, null=True)),
                ("max_nna_dist", models.FloatField(blank=True, null=True)),
                ("nna_indices", models.JSONField(blank=True, null=True)),
                ("nna_formula", models.CharField(blank=True, max_length=25, null=True)),
                ("nnas_per_formula", models.FloatField(blank=True, null=True)),
                ("nnas_per_reduced_formula", models.FloatField(blank=True, null=True)),
                ("num_nnas", models.IntegerField(blank=True, null=True)),
                (
                    "baderkit_calculation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="baderkit.baderkit",
                    ),
                ),
            ],
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.CreateModel(
            name="ElfFeatures",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("basin_types", models.JSONField(blank=True, null=True)),
                ("basin_charges", models.JSONField(blank=True, null=True)),
                ("basin_volumes", models.JSONField(blank=True, null=True)),
                ("maxima_frac", models.JSONField(blank=True, null=True)),
                ("maxima_center_frac", models.JSONField(blank=True, null=True)),
                ("maxima_elf_values", models.JSONField(blank=True, null=True)),
                ("attractor_shapes", models.JSONField(blank=True, null=True)),
                ("attractor_depths", models.JSONField(blank=True, null=True)),
                ("nearest_atoms", models.JSONField(blank=True, null=True)),
                ("nearest_atom_species", models.JSONField(blank=True, null=True)),
                ("heavily_polarized", models.JSONField(blank=True, null=True)),
                ("basin_atom_dists", models.JSONField(blank=True, null=True)),
                ("basin_dists_beyond_atoms", models.JSONField(blank=True, null=True)),
                (
                    "elf_labeler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="baderkit.elflabeler",
                    ),
                ),
            ],
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.CreateModel(
            name="ElfRadii",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("method_kwargs", models.JSONField(blank=True, null=True)),
                (
                    "baderkit_calculation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="baderkit.baderkit",
                    ),
                ),
            ],
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.CreateModel(
            name="AtomElfRadii",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("atom_radii", models.FloatField()),
                (
                    "atom_bond_types",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                ("species", models.JSONField(blank=True, null=True)),
                (
                    "elf_radii",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="baderkit.elfradii",
                    ),
                ),
            ],
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.CreateModel(
            name="AllElfRadii",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("site_indices", models.IntegerField()),
                ("neigh_indices", models.IntegerField()),
                ("all_radii", models.FloatField()),
                ("site_frac_coords", models.JSONField()),
                ("neigh_frac_coords", models.JSONField()),
                (
                    "all_bond_types",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "elf_radii",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="baderkit.elfradii",
                    ),
                ),
            ],
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
    ]
