# Generated by Django 4.2.7 on 2025-10-28 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_components", "0004_websitepagevisit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElfAnalysis",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("source", models.JSONField(blank=True, null=True)),
                ("structure", models.TextField(blank=True, null=True)),
                ("nsites", models.IntegerField(blank=True, null=True)),
                ("nelements", models.IntegerField(blank=True, null=True)),
                ("elements", models.JSONField(blank=True, null=True)),
                (
                    "chemical_system",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("density", models.FloatField(blank=True, null=True)),
                ("density_atomic", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("volume_molar", models.FloatField(blank=True, null=True)),
                (
                    "formula_full",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "formula_reduced",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "formula_anonymous",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cutoff_kwargs", models.JSONField(blank=True, null=True)),
                ("bifurcation_graph", models.JSONField(blank=True, null=True)),
                ("labeled_structure", models.JSONField(blank=True, null=True)),
                ("quasi_atom_structure", models.JSONField(blank=True, null=True)),
                ("atom_elf_radii", models.JSONField(blank=True, null=True)),
                ("quasi_atom_elf_radii", models.JSONField(blank=True, null=True)),
                ("oxidation_states", models.JSONField(blank=True, null=True)),
                ("charges", models.JSONField(blank=True, null=True)),
                ("volumes", models.JSONField(blank=True, null=True)),
                ("spin_system", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "spacegroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core_components.spacegroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpinElfAnalysis",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("source", models.JSONField(blank=True, null=True)),
                ("structure", models.TextField(blank=True, null=True)),
                ("nsites", models.IntegerField(blank=True, null=True)),
                ("nelements", models.IntegerField(blank=True, null=True)),
                ("elements", models.JSONField(blank=True, null=True)),
                (
                    "chemical_system",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("density", models.FloatField(blank=True, null=True)),
                ("density_atomic", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("volume_molar", models.FloatField(blank=True, null=True)),
                (
                    "formula_full",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "formula_reduced",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "formula_anonymous",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cutoff_kwargs", models.JSONField(blank=True, null=True)),
                ("total_labeled_structure", models.JSONField(blank=True, null=True)),
                ("total_quasi_atom_structure", models.JSONField(blank=True, null=True)),
                ("average_atom_elf_radii", models.JSONField(blank=True, null=True)),
                ("total_oxidation_states", models.JSONField(blank=True, null=True)),
                ("total_charges", models.JSONField(blank=True, null=True)),
                ("average_volumes", models.JSONField(blank=True, null=True)),
                (
                    "analysis_down",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spin_analysis",
                        to="baderkit.elfanalysis",
                    ),
                ),
                (
                    "analysis_up",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spin_analysis",
                        to="baderkit.elfanalysis",
                    ),
                ),
                (
                    "spacegroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core_components.spacegroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ElfFeatures",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("source", models.JSONField(blank=True, null=True)),
                (
                    "domain_subtype",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "feature_type",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                ("frac_coords", models.JSONField(blank=True, null=True)),
                ("average_frac_coords", models.JSONField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("depth", models.FloatField(blank=True, null=True)),
                ("depth_to_infinite", models.FloatField(blank=True, null=True)),
                ("charge", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("nearest_atom", models.FloatField(blank=True, null=True)),
                (
                    "nearest_atom_type",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                ("atom_distance", models.FloatField(blank=True, null=True)),
                (
                    "quasi_atom_structure_index",
                    models.IntegerField(blank=True, null=True),
                ),
                ("min_surface_dist", models.FloatField(blank=True, null=True)),
                ("avg_surface_dist", models.FloatField(blank=True, null=True)),
                ("dist_beyond_atom", models.FloatField(blank=True, null=True)),
                ("coord_number", models.IntegerField(blank=True, null=True)),
                ("coord_atom_indices", models.JSONField(blank=True, null=True)),
                ("coord_atom_species", models.JSONField(blank=True, null=True)),
                ("quasi_coord_number", models.IntegerField(blank=True, null=True)),
                ("coord_quasi_atom_indices", models.JSONField(blank=True, null=True)),
                ("coord_quasi_atom_species", models.JSONField(blank=True, null=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elf_features",
                        to="baderkit.elfanalysis",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
