# Generated by Django 5.2.15 on 2026-06-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baderkit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="elflabeler",
            name="max_basin_dist",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
