# Generated by Django 3.1.1 on 2020-12-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=12)),
                ('nsites', models.IntegerField()),
                ('pretty_formula', models.CharField(max_length=25)),
                ('final_energy', models.FloatField(blank=True, null=True)),
                ('final_energy_per_atom', models.FloatField(blank=True, null=True)),
                ('formation_energy_per_atom', models.FloatField(blank=True, null=True)),
                ('e_above_hull', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField()),
                ('structure', models.TextField()),
            ],
        ),
    ]
