# Generated by Django 4.2.7 on 2024-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bandstructurecalc",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="densityofstatescalc",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diffusionanalysis",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dynamics",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dynamicsionicstep",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ionicstep",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationimage",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relaxation",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staticenergy",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
