# Generated by Django 4.1.5 on 2023-12-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="badelfanalysis",
            name="electride_dim",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
