# Generated by Django 4.2.7 on 2025-01-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemicalsystemsearch",
            name="fitness_field",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="chemicalsystemsearch",
            name="fitness_function",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="chemicalsystemsearch",
            name="target_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fixedcompositionsearch",
            name="fitness_function",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="fixedcompositionsearch",
            name="target_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="steadystatesource",
            name="active_workitem_ids",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="steadystatesource",
            name="target_history",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="steadystatesource",
            name="target_time_history",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="steadystatesource",
            name="workitem_ids_history",
            field=models.JSONField(default=list),
        ),
    ]
