# Generated by Django 4.1.5 on 2023-12-08 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badelfanalysis",
            name="elf_connect_cutoff",
        ),
    ]
