# Generated by Django 4.2.7 on 2024-10-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedcompositionsearch",
            name="fitness_function",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="fixedcompositionsearch",
            name="target_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
