# Generated by Django 4.2.7 on 2025-03-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedcompositionsearch",
            name="stop_conditions",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
