# Generated by Django 4.2.7 on 2024-02-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_badelf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badelf",
            name="elf_connect_cutoff",
        ),
        migrations.AddField(
            model_name="badelf",
            name="dim_cutoffs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_structure",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="badelf",
            name="electride_dim",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
