# Generated by Django 4.1.5 on 2023-12-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0002_remove_badelfanalysis_elf_connect_cutoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="badelfanalysis",
            name="elf_connect_cutoff",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
