# Generated by Django 4.2.2 on 2023-09-19 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0002_alter_bandstructurecalc_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logpow",
            name="fingerprint_featmorganbv",
        ),
        migrations.RemoveField(
            model_name="logpow",
            name="fingerprint_torsionbv",
        ),
    ]
