# Generated by Django 4.2.7 on 2024-10-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_bandstructurecalc_fingerprint_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bandstructurecalc",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
        migrations.RenameField(
            model_name="densityofstatescalc",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
        migrations.RenameField(
            model_name="diffusionanalysis",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
        migrations.RenameField(
            model_name="dynamics",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
        migrations.RenameField(
            model_name="dynamicsionicstep",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
        migrations.RenameField(
            model_name="ionicstep",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
        migrations.RenameField(
            model_name="migrationimage",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
        migrations.RenameField(
            model_name="relaxation",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
        migrations.RenameField(
            model_name="staticenergy",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
    ]
