# Generated by Django 4.2.7 on 2025-03-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_fixedcompositionsearch_stop_conditions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fixedcompositionsearch",
            name="best_survival_cutoff",
        ),
        migrations.RemoveField(
            model_name="fixedcompositionsearch",
            name="convergence_cutoff",
        ),
        migrations.RemoveField(
            model_name="fixedcompositionsearch",
            name="expected_structure",
        ),
        migrations.RemoveField(
            model_name="fixedcompositionsearch",
            name="max_structures",
        ),
        migrations.RemoveField(
            model_name="fixedcompositionsearch",
            name="min_structures_exact",
        ),
    ]
