# Generated by Django 4.1.5 on 2023-11-16 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0002_warrenpopulationanalysis"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WarrenPopulationAnalysis",
        ),
    ]
