# Generated by Django 4.2.7 on 2025-03-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflows",
            "0003_remove_fixedcompositionsearch_best_survival_cutoff_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variablensitescompositionsearch",
            name="best_survival_cutoff",
        ),
        migrations.RemoveField(
            model_name="variablensitescompositionsearch",
            name="convergence_cutoff",
        ),
        migrations.RemoveField(
            model_name="variablensitescompositionsearch",
            name="expected_structure",
        ),
        migrations.RemoveField(
            model_name="variablensitescompositionsearch",
            name="max_structures",
        ),
        migrations.RemoveField(
            model_name="variablensitescompositionsearch",
            name="min_structures_exact",
        ),
        migrations.AddField(
            model_name="variablensitescompositionsearch",
            name="stop_conditions",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
