# Generated by Django 4.2.7 on 2024-10-31 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_components", "0002_alter_fingerprint_id_alter_fingerprintpool_id"),
        ("workflows", "0003_stagedcalculation"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagedcalculation",
            name="chemical_system",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="stagedcalculation",
            name="density",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stagedcalculation",
            name="density_atomic",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stagedcalculation",
            name="elements",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stagedcalculation",
            name="formula_anonymous",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stagedcalculation",
            name="formula_full",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stagedcalculation",
            name="formula_reduced",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stagedcalculation",
            name="nelements",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stagedcalculation",
            name="nsites",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stagedcalculation",
            name="spacegroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core_components.spacegroup",
            ),
        ),
        migrations.AddField(
            model_name="stagedcalculation",
            name="structure",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stagedcalculation",
            name="volume",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stagedcalculation",
            name="volume_molar",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
