# Generated by Django 4.2.7 on 2026-01-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0003_workitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkItem",
        ),
        migrations.RemoveField(
            model_name="bandstructurecalc",
            name="run_id",
        ),
        migrations.RemoveField(
            model_name="chemicalsystemsearch",
            name="run_id",
        ),
        migrations.RemoveField(
            model_name="densityofstatescalc",
            name="run_id",
        ),
        migrations.RemoveField(
            model_name="diffusionanalysis",
            name="run_id",
        ),
        migrations.RemoveField(
            model_name="dynamics",
            name="run_id",
        ),
        migrations.RemoveField(
            model_name="fixedcompositionsearch",
            name="run_id",
        ),
        migrations.RemoveField(
            model_name="migrationhop",
            name="run_id",
        ),
        migrations.RemoveField(
            model_name="relaxation",
            name="run_id",
        ),
        migrations.RemoveField(
            model_name="staticenergy",
            name="run_id",
        ),
        migrations.RemoveField(
            model_name="variablensitescompositionsearch",
            name="run_id",
        ),
        migrations.AddField(
            model_name="bandstructurecalc",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="chemicalsystemsearch",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="densityofstatescalc",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="diffusionanalysis",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="dynamics",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="fixedcompositionsearch",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="migrationhop",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="relaxation",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="staticenergy",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="variablensitescompositionsearch",
            name="status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
