# Generated by Django 4.2.2 on 2023-09-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0003_remove_logpow_fingerprint_featmorganbv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logpow",
            name="log_d_trained",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
