# Generated by Django 4.2.7 on 2024-10-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0004_stagedcalculation_chemical_system_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagedcalculation",
            name="failed_subworkflow",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
