# Generated by Django 4.2.7 on 2024-11-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0005_stagedcalculation_failed_subworkflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="steadystatesource",
            name="active_workitem_ids",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="steadystatesource",
            name="recent_workitem_ids",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="steadystatesource",
            name="target_history",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="steadystatesource",
            name="target_time_history",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="steadystatesource",
            name="workitem_ids_history",
            field=models.JSONField(default=list),
        ),
    ]
