# Generated by Django 4.1.5 on 2023-11-21 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0005_badelfanalysis_delete_warrenpopulationanalysis"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BadElfAnalysis",
        ),
    ]
