# Generated by Django 4.2.7 on 2024-11-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0006_steadystatesource_active_workitem_ids_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="steadystatesource",
            name="recent_workitem_ids",
        ),
    ]
