# Generated by Django 4.2.7 on 2026-02-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0006_simmateworker_workitem_worker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dynamicsionicstep",
            name="source",
        ),
        migrations.RemoveField(
            model_name="ionicstep",
            name="source",
        ),
        migrations.RemoveField(
            model_name="steadystatesource",
            name="source",
        ),
    ]
