# Generated by Django 4.2.7 on 2024-11-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0007_remove_steadystatesource_recent_workitem_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steadystatesource",
            name="target_time_history",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
