# Generated by Django 5.2.11 on 2026-03-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0007_remove_dynamicsionicstep_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bandstructurecalc",
            name="is_invalid_structure",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="densityofstatescalc",
            name="is_invalid_structure",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diffusionanalysis",
            name="is_invalid_structure",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dynamics",
            name="is_invalid_structure",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dynamicsionicstep",
            name="is_invalid_structure",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ionicstep",
            name="is_invalid_structure",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="migrationimage",
            name="is_invalid_structure",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relaxation",
            name="is_invalid_structure",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staticenergy",
            name="is_invalid_structure",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
