# Generated by Django 4.2.7 on 2024-11-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0008_alter_steadystatesource_target_time_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemicalsystemsearch",
            name="fitness_field",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="chemicalsystemsearch",
            name="fitness_function",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="chemicalsystemsearch",
            name="target_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
