# Generated by Django 5.2.11 on 2026-03-27 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cas_registry", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="casregistrymolecule",
            name="physical_state",
        ),
        migrations.RemoveField(
            model_name="casregistrymolecule",
            name="pubchem_id",
        ),
    ]
