# This yaml file configures DigitalOcean's app platform. It was made many
# manually following along with the guide in the web interface (see the README)
# and then copying over the resulting app-spec.
# For details on the specification see... 
#   https://docs.digitalocean.com/products/app-platform/references/app-specification-reference/

databases:
- engine: PG
  name: db-test
  num_nodes: 1
  size: basic-xs
  version: "12"
name: monkfish-app
region: nyc
services:
- envs:
  - key: DJANGO_ALLOWED_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: ${APP_DOMAIN}
  - key: DJANGO_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:rwoXEbQyIu3MgO2pXNrloPiAFScgcHFt:KbyRWPP/XvcER/krbkUndaCvo32x8Aoh+f94EgWmEyOf3m3mIRcWh2PIr7RdE2pdYNL3rpkLKLSlVlp5HFP2VVAC]
  http_port: 8080
  image:
    registry: jacksund
    registry_type: DOCKER_HUB
    repository: simmate
    tag: v0.9.0
  instance_count: 1
  instance_size_slug: basic-xxs
  name: jacksund-simmate
  routes:
  - path: /
  run_command: conda run -n simmate_dev gunicorn --worker-tmp-dir /dev/shm simmate.website.core.wsgi
