# Generated by Django 3.1.5 on 2021-02-16 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpiricalMeasures',
            fields=[
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('C', 'Completed'), ('F', 'Failed')], default='S', max_length=1)),
                ('pathway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='diffusion.pathway')),
                ('nsites_unitcell', models.IntegerField()),
                ('nsites_888', models.IntegerField()),
                ('nsites_101010', models.IntegerField()),
                ('nsites_121212', models.IntegerField()),
                ('atomic_fraction', models.FloatField()),
                ('distance_rel_min', models.FloatField()),
                ('oxidation_state', models.IntegerField()),
                ('dimensionality', models.IntegerField()),
                ('dimensionality_cumlengths', models.IntegerField()),
                ('ewald_energy', models.FloatField()),
                ('ionic_radii_overlap_cations', models.FloatField()),
                ('ionic_radii_overlap_anions', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='relativedistancevsdmin',
            name='pathway',
        ),
        migrations.DeleteModel(
            name='DimensionalityLarsen',
        ),
        migrations.DeleteModel(
            name='RelativeDistanceVsDmin',
        ),
    ]
