# Generated by Django 3.1.5 on 2021-02-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0002_auto_20210216_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empiricalmeasures',
            name='dimensionality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empiricalmeasures',
            name='dimensionality_cumlengths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empiricalmeasures',
            name='ewald_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empiricalmeasures',
            name='ionic_radii_overlap_anions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empiricalmeasures',
            name='ionic_radii_overlap_cations',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
