services:

  # ---------------------------------------------------------

  # WEB SERVER
  simmate-gunicorn-service:
    image: simmate:latest
    build:
       context: ../..
       dockerfile: envs/docker/simmate.dockerfile
    ports:
      - 8000:8000
    volumes:
      - staticfiles:/root/simmate/staticfiles
    environment: &simmate-env
      # --- CORE SETTINGS ---
      SIMMATE__DATABASE__ENGINE: django.db.backends.postgresql
      SIMMATE__DATABASE__HOST: simmate-postgres-service
      SIMMATE__DATABASE__PORT: 5432
      SIMMATE__DATABASE__NAME: simmate_prod
      SIMMATE__DATABASE__USER: example_user
      SIMMATE__DATABASE__PASSWORD: example123
      SIMMATE__POSTGRES_RDKIT_EXTENSION: "True"

      # --- WEB UI SETTINGS ---
      SIMMATE__WEBSITE__ALLOWED_HOSTS: "*"
      SIMMATE__WEBSITE__CSRF_TRUSTED_ORIGINS: "http://localhost:1337"
      SIMMATE__WEBSITE__DEBUG: "True"
      SIMMATE__WEBSITE__REQUIRE_LOGIN: "True"
      SIMMATE__WEBSITE__REQUIRE_LOGIN_INTERNAL: "microsoft"
      SIMMATE__WEBSITE__REQUIRE_LOGIN_EXCEPTIONS: "/apps/example(.*)$"
      SIMMATE__WEBSITE__SOCIAL_OAUTH__MICROSOFT__CLIENT_ID: "example_user"
      SIMMATE__WEBSITE__SOCIAL_OAUTH__MICROSOFT__SECRET: "example123"

      # --- OPTIONAL / ADVANCED ---
      # SIMMATE__APPS: "simmate.apps.configs.AflowConfig simmate.apps.configs.CodConfig"
      # SIMMATE__CHATBOT__ENDPOINT: "https://example.azure-api.net/"
      # SIMMATE__CHATBOT__API_KEY: "abc123"
    depends_on:
      - simmate-postgres-service

  # --------------------------------------------------------

  # STATIC FILE SERVER
  simmate-nginx-service:
    image: simmate-nginx:latest
    build:
       context: ../..
       dockerfile: envs/docker/simmate-nginx.dockerfile
    volumes:
      - staticfiles:/staticfiles
    ports:
      - 1337:80
    depends_on:
      - simmate-gunicorn-service

  # --------------------------------------------------------

  # SCHEDULER (for periodic tasks)
  simmate-scheduler-service:
    image: simmate:latest
    command: ["simmate", "compute", "start-schedules"]
    environment: *simmate-env
    depends_on:
      - simmate-postgres-service

  # --------------------------------------------------------

  # WORKER (for workflow execution)
  simmate-worker-service:
    image: simmate:latest
    command: ["simmate", "compute", "start-worker"]
    environment: *simmate-env
    volumes:
      - worker-data:/simmate_workers
    depends_on:
      - simmate-postgres-service

  # --------------------------------------------------------

  # DATABASE SERVER
  simmate-postgres-service:
    image: informaticsmatters/rdkit-cartridge-debian:latest
    environment:
      POSTGRES_DB: simmate_prod
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example123
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - 5433:5432

# ------------

volumes:
  postgres-data:
  staticfiles:
  worker-data:
