# docs https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: 🐞 Bug report
description: Report any errors or problems with your example test case and/or full error messages.
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: |

        **PLEASE READ THIS PARAGRAPH - this helps us identify the root cause and fix the issue:**

        If you have a question about getting started or how a feature works, please report your question via our [Discussions Page](https://github.com/jacksund/simmate/discussions/categories/q-a). In many cases, an error message corresponds to using Simmate incorrectly rather than a bug. If you're unsure, stick to a discussion post. We'll then investigate any issues and open a bug report when necessary.

        If you indeed have a bug, it helps to include things like the structure you used, the code, & input files while completing this form. For the code, try not to add long scripts if the error is only happening in one small part of it. Instead, try to generate your issue/error with as little code as possible or even using a illustrative example.

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: Provide your [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/mcve) example here.
      placeholder: Insert code here

  - type: textarea
    attributes:
      label: Error
      description: Provide the full error message, including the full exception traceback.
      placeholder: Copy complete stack trace and error message here, including log output if applicable.
      value: |
        ``` python
        Copy complete error message here.
        ```

  - type: textarea
    attributes:
      label: Versions
      description: "If you can access them, input your system info. HINT: you can find python and simmate versions with the command `conda list python` and `conda list simmate` while in your working env."
      value: |
        - Operating System:
        - Python version:
        - Simmate version:
 
  - type: textarea
    attributes:
      label: Additional details
      description: Add any other context about the problem here. If you have a suggested fix, you can include it here.

  - type: markdown
    attributes:
      value: Thank you for using our software and helping us improve it!!
