apiVersion: v1
kind: Service
metadata:
  name: simmate-postgres-ext-service
  {{- if or (eq .Values.platform "digitalocean") (eq .Values.platform "aws") }}
  annotations:
    # limit access to resources on same VPC
    {{- if eq .Values.platform "digitalocean" }}
    service.beta.kubernetes.io/do-loadbalancer-network: "INTERNAL"
    {{- else if eq .Values.platform "aws" }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    {{- end }}
  {{- end }}
spec:
  type: LoadBalancer
  selector:
    app: simmate-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
