apiVersion: v1
kind: Service
metadata:
  name: simmate-postgres-ext-service
  annotations:
    # service.beta.kubernetes.io/aws-load-balancer-name: custom-name-123
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: simmate-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
