# Generated by Django 5.2.11 on 2026-03-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_explorer", "0008_bandstructurecalc_is_invalid_structure_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bandstructurecalc",
            table="workflows_bandstructurecalc",
        ),
        migrations.AlterModelTable(
            name="chemicalsystemsearch",
            table="workflows_chemicalsystemsearch",
        ),
        migrations.AlterModelTable(
            name="densityofstatescalc",
            table="workflows_densityofstatescalc",
        ),
        migrations.AlterModelTable(
            name="diffusionanalysis",
            table="workflows_diffusionanalysis",
        ),
        migrations.AlterModelTable(
            name="dynamics",
            table="workflows_dynamics",
        ),
        migrations.AlterModelTable(
            name="dynamicsionicstep",
            table="workflows_dynamicsionicstep",
        ),
        migrations.AlterModelTable(
            name="fixedcompositionsearch",
            table="workflows_fixedcompositionsearch",
        ),
        migrations.AlterModelTable(
            name="ionicstep",
            table="workflows_ionicstep",
        ),
        migrations.AlterModelTable(
            name="migrationhop",
            table="workflows_migrationhop",
        ),
        migrations.AlterModelTable(
            name="migrationimage",
            table="workflows_migrationimage",
        ),
        migrations.AlterModelTable(
            name="populationanalysis",
            table="workflows_populationanalysis",
        ),
        migrations.AlterModelTable(
            name="relaxation",
            table="workflows_relaxation",
        ),
        migrations.AlterModelTable(
            name="staticenergy",
            table="workflows_staticenergy",
        ),
        migrations.AlterModelTable(
            name="steadystatesource",
            table="workflows_steadystatesource",
        ),
        migrations.AlterModelTable(
            name="variablensitescompositionsearch",
            table="workflows_variablensitescompositionsearch",
        ),
    ]
