# Generated by Django 5.2.12 on 2026-05-23 19:37

import django.db.models.deletion
import simmate.database.core.archive
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_feedback"),
        ("workflow_explorer", "0009_alter_bandstructurecalc_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staticenergy",
            name="band_gap",
        ),
        migrations.RemoveField(
            model_name="staticenergy",
            name="conduction_band_minimum",
        ),
        migrations.RemoveField(
            model_name="staticenergy",
            name="energy_fermi",
        ),
        migrations.RemoveField(
            model_name="staticenergy",
            name="is_gap_direct",
        ),
        migrations.RemoveField(
            model_name="staticenergy",
            name="valence_band_maximum",
        ),
        migrations.CreateModel(
            name="StagedRelaxStatic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_time", models.FloatField(blank=True, null=True)),
                ("queue_time", models.FloatField(blank=True, null=True)),
                (
                    "workflow_name",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "workflow_version",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                (
                    "computer_system",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                ("directory", models.CharField(blank=True, max_length=250, null=True)),
                ("run_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("status", models.CharField(blank=True, max_length=10, null=True)),
                ("corrections", models.JSONField(blank=True, null=True)),
                ("source", models.JSONField(blank=True, null=True)),
                ("structure", models.TextField(blank=True, null=True)),
                ("nsites", models.IntegerField(blank=True, null=True)),
                ("nelements", models.IntegerField(blank=True, null=True)),
                ("elements", models.JSONField(blank=True, null=True)),
                (
                    "chemical_system",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("is_invalid_structure", models.BooleanField(blank=True, null=True)),
                ("density", models.FloatField(blank=True, null=True)),
                ("density_atomic", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("volume_molar", models.FloatField(blank=True, null=True)),
                (
                    "formula_full",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "formula_reduced",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "formula_anonymous",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("site_forces", models.JSONField(blank=True, null=True)),
                ("lattice_stress", models.JSONField(blank=True, null=True)),
                ("site_force_norm_max", models.FloatField(blank=True, null=True)),
                ("site_forces_norm", models.FloatField(blank=True, null=True)),
                ("site_forces_norm_per_atom", models.FloatField(blank=True, null=True)),
                ("lattice_stress_norm", models.FloatField(blank=True, null=True)),
                (
                    "lattice_stress_norm_per_atom",
                    models.FloatField(blank=True, null=True),
                ),
                ("energy", models.FloatField(blank=True, null=True)),
                ("energy_per_atom", models.FloatField(blank=True, null=True)),
                ("energy_above_hull", models.FloatField(blank=True, null=True)),
                ("is_stable", models.BooleanField(blank=True, null=True)),
                ("decomposes_to", models.JSONField(blank=True, null=True)),
                ("formation_energy", models.FloatField(blank=True, null=True)),
                ("formation_energy_per_atom", models.FloatField(blank=True, null=True)),
                (
                    "subworkflow_runs",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "spacegroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.spacegroup",
                    ),
                ),
            ],
            options={
                "db_table": "workflows_stagedrelaxstatic",
            },
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
    ]
