# Generated by Django 5.2.12 on 2026-05-24 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_explorer", "0010_remove_staticenergy_band_gap_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relaxation",
            name="band_gap",
        ),
        migrations.RemoveField(
            model_name="relaxation",
            name="conduction_band_minimum",
        ),
        migrations.RemoveField(
            model_name="relaxation",
            name="energy_fermi",
        ),
        migrations.RemoveField(
            model_name="relaxation",
            name="is_gap_direct",
        ),
        migrations.RemoveField(
            model_name="relaxation",
            name="valence_band_maximum",
        ),
    ]
