# Generated by Django 5.2.12 on 2026-08-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_explorer", "0012_bandstructurecalc_submitted_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workitem",
            name="command_not_found_failures",
        ),
    ]
