# Generated by Django 5.2.17 on 2026-09-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_explorer", "0013_remove_workitem_command_not_found_failures"),
    ]

    operations = [
        migrations.AddField(
            model_name="workitem",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="simmateworker",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
