# Generated by Django 5.2.17 on 2026-09-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_explorer", "0014_workitem_started_at_alter_simmateworker_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workitem",
            name="worker",
        ),
        migrations.DeleteModel(
            name="SimmateWorker",
        ),
        migrations.DeleteModel(
            name="WorkItem",
        ),
    ]
