# Generated by Django 5.2.11 on 2026-03-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cod", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codstructure",
            name="is_invalid_structure",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="codstructure",
            name="chemical_system",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="codstructure",
            name="formula_anonymous",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="codstructure",
            name="formula_full",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="codstructure",
            name="formula_reduced",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="codstructure",
            name="has_implicit_hydrogens",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="codstructure",
            name="is_ordered",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
