# Generated by Django 5.2.11 on 2026-03-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cod", "0002_codstructure_is_invalid_structure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codstructure",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
