# Generated by Django 4.2.7 on 2025-10-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baderkit", "0001_initial"),
        ("badelf", "0001_initial"),
        ("core_components", "0004_websitepagevisit"),
    ]

    operations = [
        migrations.AddField(
            model_name="badelf",
            name="elf_analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badelf",
                to="baderkit.elfanalysis",
            ),
        ),
        migrations.AddField(
            model_name="badelf",
            name="spacegroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core_components.spacegroup",
            ),
        ),
    ]
