# Generated by Django 4.2.7 on 2024-02-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badelf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="badelf",
            name="electrides_per_formula",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
