# Generated by Django 4.2.7 on 2025-01-22 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badelf", "0003_badelf_electrides_per_reduced_formula"),
    ]

    operations = [
        migrations.AddField(
            model_name="badelf",
            name="elf_maxima",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ElfIonicRadii",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("source", models.JSONField(blank=True, null=True)),
                ("site_index", models.IntegerField()),
                ("neigh_index", models.IntegerField()),
                ("radius", models.FloatField()),
                (
                    "bad_elf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ionic_radii",
                        to="badelf.badelf",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
