# Generated by Django 4.2.7 on 2024-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badelf", "0003_badelf_electrides_per_reduced_formula"),
    ]

    operations = [
        migrations.AddField(
            model_name="badelf",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
