# Generated by Django 4.2.7 on 2025-01-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badelf", "0004_elfionicradii"),
    ]

    operations = [
        migrations.AddField(
            model_name="badelf",
            name="elf_maxima",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
