# Generated by Django 4.2.7 on 2025-02-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badelf", "0004_badelf_elf_maxima_elfionicradii"),
    ]

    operations = [
        migrations.AddField(
            model_name="badelf",
            name="covalent_algorithm",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="covalent_atom_pairs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="ncovalent_bonds",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
