# Generated by Django 4.2.7 on 2025-03-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badelf", "0004_badelf_elf_maxima_elfionicradii"),
    ]

    operations = [
        migrations.RenameField(
            model_name="badelf",
            old_name="dim_cutoffs",
            new_name="electride_dim_cutoffs",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="atomic_volumes",
            new_name="site_volumes",
        ),
        migrations.AddField(
            model_name="badelf",
            name="atom_oxidation_states",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="charges_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="charges_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="coord_envs_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="coord_envs_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="differing_spin",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_dim_cutoffs_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_dim_cutoffs_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_dim_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_dim_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="elf_maxima_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="elf_maxima_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="labeled_structure",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="labeled_structure_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="labeled_structure_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="min_dists_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="min_dists_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="nelectrides_down",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="nelectrides_up",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="nelectrons_down",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="nelectrons_up",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="non_atom_charges",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="non_atom_charges_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="non_atom_charges_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="nshared_features",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="separate_spin",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_algorithm",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_atoms",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_atoms_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_atoms_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="site_volumes_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="site_volumes_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="vacuum_volume_down",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="vacuum_volume_up",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
