# Generated by Django 4.2.7 on 2025-04-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badelf", "0005_rename_dim_cutoffs_badelf_electride_dim_cutoffs_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="badelf",
            old_name="charges",
            new_name="atom_charges",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="charges_down",
            new_name="atom_charges_down",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="charges_up",
            new_name="atom_charges_up",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="coord_envs",
            new_name="atom_coord_envs",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="coord_envs_down",
            new_name="atom_coord_envs_down",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="coord_envs_up",
            new_name="atom_coord_envs_up",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="elf_maxima",
            new_name="atom_elf_maxima",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="elf_maxima_down",
            new_name="atom_elf_maxima_down",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="elf_maxima_up",
            new_name="atom_elf_maxima_up",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="min_dists",
            new_name="atom_min_dists",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="min_dists_down",
            new_name="atom_min_dists_down",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="min_dists_up",
            new_name="atom_min_dists_up",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="site_volumes",
            new_name="atom_volumes",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="site_volumes_down",
            new_name="atom_volumes_down",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="site_volumes_up",
            new_name="atom_volumes_up",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="non_atom_charges",
            new_name="electride_charges",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="non_atom_charges_down",
            new_name="electride_charges_down",
        ),
        migrations.RenameField(
            model_name="badelf",
            old_name="non_atom_charges_up",
            new_name="electride_charges_up",
        ),
        migrations.RemoveField(
            model_name="badelf",
            name="element_list",
        ),
        migrations.RemoveField(
            model_name="badelf",
            name="oxidation_states",
        ),
        migrations.AddField(
            model_name="badelf",
            name="bifurcation_graph",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="bifurcation_graph_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="bifurcation_graph_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_coord_envs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_coord_envs_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_coord_envs_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_elf_maxima",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_elf_maxima_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_elf_maxima_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_min_dists",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_min_dists_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_min_dists_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_oxidation_states",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_oxidation_states_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_oxidation_states_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_volumes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_volumes_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="electride_volumes_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_charges",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_charges_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_charges_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_coord_envs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_coord_envs_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_coord_envs_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_elf_maxima",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_elf_maxima_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_elf_maxima_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_min_dists",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_min_dists_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_min_dists_up",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_separation_method",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_types",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_volumes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_volumes_down",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badelf",
            name="shared_feature_volumes_up",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
