# Generated by Django 4.2.7 on 2025-03-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "badelf",
            "0005_badelf_covalent_algorithm_badelf_covalent_atom_pairs_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="badelf",
            old_name="covalent_algorithm",
            new_name="shared_bond_algorithm",
        ),
    ]
