# Generated by Django 5.2.11 on 2026-04-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdb", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pdbligand",
            old_name="type",
            new_name="monomer_type",
        ),
        migrations.RenameField(
            model_name="pdbligand",
            old_name="protein_ids",
            new_name="protein_ids_original",
        ),
        migrations.AddField(
            model_name="pdbligand",
            name="created_at_original",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="pdbligand",
            name="updated_at_original",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="pdbligand",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="pdbligand",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
