apiVersion: apps/v1
kind: Deployment
metadata:
  name: simmate-nginx-deployment
  labels:
    app: simmate-nginx
spec:
  selector:
    matchLabels:
      app: simmate-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: simmate-nginx
        # bug-fix: https://stackoverflow.com/questions/46336852/
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: simmate-nginx
          image: simmate/simmate-nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: simmate-gunicorn-staticfiles
              mountPath: /staticfiles
          resources:
            requests:
              memory: {{ .Values.nginx.resources.requests.memory }}
              cpu: {{ .Values.nginx.resources.requests.cpu }}
              ephemeral-storage: {{ .Values.nginx.resources.requests.ephemeral }}
            limits:
              memory: {{ .Values.nginx.resources.limits.memory }}
              cpu: {{ .Values.nginx.resources.limits.cpu }}
              ephemeral-storage: {{ .Values.nginx.resources.limits.ephemeral }}
      volumes:
        - name: simmate-gunicorn-staticfiles
          persistentVolumeClaim:
            claimName: simmate-gunicorn-staticfiles
