apiVersion: apps/v1
kind: Deployment
metadata:
  name: simmate-nginx-deployment
  labels:
    app: simmate-nginx
spec:
  selector:
    matchLabels:
      app: simmate-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: simmate-nginx
        # bug-fix: https://stackoverflow.com/questions/46336852/
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: simmate-nginx
          image: jacksund/nginx:{{ .Values.version }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: simmate-gunicorn-staticfiles
              mountPath: /staticfiles
          resources:
            requests:
              memory: {{ .Values.nginx.memory.request }}
              cpu: {{ .Values.nginx.cpu.request }}
              ephemeral-storage: {{ .Values.nginx.ephemeral.request }}
            limits:
              memory: {{ .Values.nginx.memory.limit }}
              cpu: {{ .Values.nginx.cpu.limit }}
              ephemeral-storage: {{ .Values.nginx.ephemeral.limit }}
      volumes:
        - name: simmate-gunicorn-staticfiles
          persistentVolumeClaim:
            claimName: simmate-gunicorn-staticfiles
