# Generated by Django 4.2.7 on 2025-09-24 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EthereumWallet",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("ens_name", models.CharField(blank=True, max_length=50, null=True)),
                ("tokens", models.JSONField(blank=True, null=True)),
                ("ethereum_total", models.FloatField(blank=True, null=True)),
                ("stablecoin_total", models.FloatField(blank=True, null=True)),
                ("total_balance_usd", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "etherscan__wallets",
            },
        ),
        migrations.CreateModel(
            name="EthereumTransaction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("created_at_original", models.DateTimeField(blank=True, null=True)),
                ("token", models.CharField(blank=True, max_length=10, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("value_usd_original", models.FloatField(blank=True, null=True)),
                ("value_usd", models.FloatField(blank=True, null=True)),
                (
                    "from_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_recieved",
                        to="etherscan.ethereumwallet",
                    ),
                ),
                (
                    "to_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_sent",
                        to="etherscan.ethereumwallet",
                    ),
                ),
            ],
            options={
                "db_table": "etherscan__transactions",
            },
        ),
    ]
