# Generated by Django 4.2.7 on 2026-02-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_components", "0004_websitepagevisit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fingerprintpool",
            name="source",
        ),
    ]
