# Generated by Django 4.2.7 on 2025-12-14 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("source", models.JSONField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("ticker", models.TextField(blank=True, null=True)),
                ("ticker_source", models.TextField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("price_unit", models.TextField(blank=True, null=True)),
                ("global_abundance", models.FloatField(blank=True, null=True)),
                ("market_cap", models.FloatField(blank=True, null=True)),
                ("global_abundance_kg", models.FloatField(blank=True, null=True)),
                (
                    "global_abundance_mg_per_kg_crust",
                    models.FloatField(blank=True, null=True),
                ),
                ("price_per_kg", models.FloatField(blank=True, null=True)),
                ("price_1y_stats", models.JSONField(blank=True, null=True)),
                ("price_5y_stats", models.JSONField(blank=True, null=True)),
                ("price_10y_stats", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "price_catalog__market_items",
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("source", models.JSONField(blank=True, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("price_normalized", models.FloatField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("delta_10y", models.FloatField(blank=True, null=True)),
                ("delta_10y_normalized", models.FloatField(blank=True, null=True)),
                ("delta_10y_percent", models.FloatField(blank=True, null=True)),
                (
                    "delta_10y_percent_normalized",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "market_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_history",
                        to="price_catalog.marketitem",
                    ),
                ),
            ],
            options={
                "db_table": "price_catalog__price_history",
                "unique_together": {("market_item", "date")},
            },
        ),
    ]
