# Generated by Django 4.2.7 on 2025-04-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eppo_gd", "0001_setup"),
    ]

    operations = [
        migrations.CreateModel(
            name="EppoCode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("eppo_source", models.CharField(blank=True, max_length=25, null=True)),
                ("preferred_name", models.TextField(blank=True, null=True)),
                ("common_names", models.JSONField(blank=True, null=True)),
                ("other_scientific_names", models.JSONField(blank=True, null=True)),
                ("kingdom", models.TextField(blank=True, null=True)),
                ("phylum", models.TextField(blank=True, null=True)),
                ("subphylum", models.TextField(blank=True, null=True)),
                (
                    "class_name",
                    models.TextField(blank=True, db_column="class", null=True),
                ),
                ("subclass", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("order", models.TextField(blank=True, null=True)),
                ("suborder", models.TextField(blank=True, null=True)),
                ("family", models.TextField(blank=True, null=True)),
                ("subfamily", models.TextField(blank=True, null=True)),
                ("genus", models.TextField(blank=True, null=True)),
                ("species", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "eppo_gd__eppo_codes",
            },
        ),
    ]
