# Generated by Django 3.1.5 on 2021-05-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AflowStructure',
            fields=[
                ('structure_json', models.TextField()),
                ('nsites', models.IntegerField()),
                ('nelement', models.IntegerField()),
                ('chemical_system', models.CharField(max_length=25)),
                ('density', models.FloatField()),
                ('molar_volume', models.FloatField()),
                ('spacegroup', models.IntegerField()),
                ('formula_full', models.CharField(max_length=50)),
                ('formula_reduced', models.CharField(max_length=25)),
                ('formula_anonymous', models.CharField(max_length=25)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('final_energy', models.FloatField(blank=True, null=True)),
                ('final_energy_per_atom', models.FloatField(blank=True, null=True)),
                ('formation_energy_per_atom', models.FloatField(blank=True, null=True)),
                ('band_gap', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JarvisStructure',
            fields=[
                ('structure_json', models.TextField()),
                ('nsites', models.IntegerField()),
                ('nelement', models.IntegerField()),
                ('chemical_system', models.CharField(max_length=25)),
                ('density', models.FloatField()),
                ('molar_volume', models.FloatField()),
                ('spacegroup', models.IntegerField()),
                ('formula_full', models.CharField(max_length=50)),
                ('formula_reduced', models.CharField(max_length=25)),
                ('formula_anonymous', models.CharField(max_length=25)),
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('formation_energy_per_atom', models.FloatField(blank=True, null=True)),
                ('e_above_hull', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialsProjectStructure',
            fields=[
                ('structure_json', models.TextField()),
                ('nsites', models.IntegerField()),
                ('nelement', models.IntegerField()),
                ('chemical_system', models.CharField(max_length=25)),
                ('density', models.FloatField()),
                ('molar_volume', models.FloatField()),
                ('spacegroup', models.IntegerField()),
                ('formula_full', models.CharField(max_length=50)),
                ('formula_reduced', models.CharField(max_length=25)),
                ('formula_anonymous', models.CharField(max_length=25)),
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('final_energy', models.FloatField(blank=True, null=True)),
                ('final_energy_per_atom', models.FloatField(blank=True, null=True)),
                ('formation_energy_per_atom', models.FloatField(blank=True, null=True)),
                ('e_above_hull', models.FloatField(blank=True, null=True)),
                ('band_gap', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OcdStructure',
            fields=[
                ('structure_json', models.TextField()),
                ('nsites', models.IntegerField()),
                ('nelement', models.IntegerField()),
                ('chemical_system', models.CharField(max_length=25)),
                ('density', models.FloatField()),
                ('molar_volume', models.FloatField()),
                ('spacegroup', models.IntegerField()),
                ('formula_full', models.CharField(max_length=50)),
                ('formula_reduced', models.CharField(max_length=25)),
                ('formula_anonymous', models.CharField(max_length=25)),
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OqmdStructure',
            fields=[
                ('structure_json', models.TextField()),
                ('nsites', models.IntegerField()),
                ('nelement', models.IntegerField()),
                ('chemical_system', models.CharField(max_length=25)),
                ('density', models.FloatField()),
                ('molar_volume', models.FloatField()),
                ('spacegroup', models.IntegerField()),
                ('formula_full', models.CharField(max_length=50)),
                ('formula_reduced', models.CharField(max_length=25)),
                ('formula_anonymous', models.CharField(max_length=25)),
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('final_energy', models.FloatField(blank=True, null=True)),
                ('e_above_hull', models.FloatField(blank=True, null=True)),
                ('band_gap', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
