# Generated by Django 3.2.5 on 2021-08-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AflowStructure',
            fields=[
                ('structure_str', models.TextField()),
                ('nsites', models.IntegerField()),
                ('nelement', models.IntegerField()),
                ('chemical_system', models.CharField(max_length=25)),
                ('density', models.DecimalField(decimal_places=3, max_digits=7)),
                ('molar_volume', models.DecimalField(decimal_places=3, max_digits=7)),
                ('spacegroup', models.IntegerField()),
                ('formula_full', models.CharField(max_length=100)),
                ('formula_reduced', models.CharField(max_length=100)),
                ('formula_anonymous', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('final_energy', models.FloatField(blank=True, null=True)),
                ('final_energy_per_atom', models.FloatField(blank=True, null=True)),
                ('formation_energy_per_atom', models.FloatField(blank=True, null=True)),
                ('band_gap', models.FloatField(blank=True, null=True)),
                ('energy_above_hull', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodStructure',
            fields=[
                ('structure_str', models.TextField()),
                ('nsites', models.IntegerField()),
                ('nelement', models.IntegerField()),
                ('chemical_system', models.CharField(max_length=25)),
                ('density', models.DecimalField(decimal_places=3, max_digits=7)),
                ('molar_volume', models.DecimalField(decimal_places=3, max_digits=7)),
                ('spacegroup', models.IntegerField()),
                ('formula_full', models.CharField(max_length=100)),
                ('formula_reduced', models.CharField(max_length=100)),
                ('formula_anonymous', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('is_ordered', models.BooleanField()),
                ('has_implicit_hydrogens', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JarvisStructure',
            fields=[
                ('structure_str', models.TextField()),
                ('nsites', models.IntegerField()),
                ('nelement', models.IntegerField()),
                ('chemical_system', models.CharField(max_length=25)),
                ('density', models.DecimalField(decimal_places=3, max_digits=7)),
                ('molar_volume', models.DecimalField(decimal_places=3, max_digits=7)),
                ('spacegroup', models.IntegerField()),
                ('formula_full', models.CharField(max_length=100)),
                ('formula_reduced', models.CharField(max_length=100)),
                ('formula_anonymous', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('formation_energy_per_atom', models.FloatField(blank=True, null=True)),
                ('energy_above_hull', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialsProjectStructure',
            fields=[
                ('structure_str', models.TextField()),
                ('nsites', models.IntegerField()),
                ('nelement', models.IntegerField()),
                ('chemical_system', models.CharField(max_length=25)),
                ('density', models.DecimalField(decimal_places=3, max_digits=7)),
                ('molar_volume', models.DecimalField(decimal_places=3, max_digits=7)),
                ('spacegroup', models.IntegerField()),
                ('formula_full', models.CharField(max_length=100)),
                ('formula_reduced', models.CharField(max_length=100)),
                ('formula_anonymous', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('final_energy', models.FloatField(blank=True, null=True)),
                ('final_energy_per_atom', models.FloatField(blank=True, null=True)),
                ('formation_energy_per_atom', models.FloatField(blank=True, null=True)),
                ('energy_above_hull', models.FloatField(blank=True, null=True)),
                ('band_gap', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OqmdStructure',
            fields=[
                ('structure_str', models.TextField()),
                ('nsites', models.IntegerField()),
                ('nelement', models.IntegerField()),
                ('chemical_system', models.CharField(max_length=25)),
                ('density', models.DecimalField(decimal_places=3, max_digits=7)),
                ('molar_volume', models.DecimalField(decimal_places=3, max_digits=7)),
                ('spacegroup', models.IntegerField()),
                ('formula_full', models.CharField(max_length=100)),
                ('formula_reduced', models.CharField(max_length=100)),
                ('formula_anonymous', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('final_energy', models.FloatField(blank=True, null=True)),
                ('energy_above_hull', models.FloatField(blank=True, null=True)),
                ('band_gap', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
