# Generated by Django 5.2.12 on 2026-03-21 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import simmate.database.core.archive
import simmate.database.core.html_mixin


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_fingerprintpool_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("message", models.TextField()),
                ("notification_type", models.CharField(max_length=100)),
                ("is_read", models.BooleanField(default=False)),
                ("target_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "simmate_notifications",
            },
            bases=(
                models.Model,
                simmate.database.core.html_mixin.HTMLMixin,
                simmate.database.core.archive.ArchiveMixin,
            ),
        ),
    ]
