# Generated by Django 5.2.12 on 2026-03-21 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import simmate.database.core.archive


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("message", models.TextField()),
                ("url_path", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "django_website_feedback",
            },
            bases=(
                models.Model,
                simmate.database.core.archive.ArchiveMixin,
            ),
        ),
    ]
