# Generated by Django 5.2.17 on 2026-09-28 21:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import simmate.database.core.archive


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SimmateWorker",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("shutdown_flag", models.BooleanField(default=False)),
                ("ncores", models.FloatField(blank=True, null=True)),
                ("ram", models.FloatField(blank=True, null=True)),
                (
                    "computer_system",
                    models.CharField(blank=True, max_length=75, null=True),
                ),
                ("directory", models.CharField(blank=True, max_length=250, null=True)),
                ("tags", models.JSONField(default=list)),
                ("nitems_max", models.IntegerField(blank=True, null=True)),
                ("timeout", models.FloatField(blank=True, null=True)),
                ("close_on_empty_queue", models.BooleanField(default=False)),
                ("waittime_on_empty_queue", models.FloatField(default=15)),
                ("startup_method", models.TextField(blank=True, null=True)),
                ("nitems_completed", models.IntegerField(blank=True, null=True)),
                ("total_up_time", models.FloatField(blank=True, null=True)),
                ("total_workflow_time", models.FloatField(blank=True, null=True)),
                ("idle_percent", models.FloatField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compute__workers",
            },
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tags", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("R", "Running"),
                            ("C", "Cancelled"),
                            ("E", "Errored"),
                            ("F", "Finished"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("fxn", models.BinaryField()),
                ("args", models.BinaryField(default=b"\x80\x05]\x94.")),
                ("kwargs", models.BinaryField(default=b"\x80\x05}\x94.")),
                ("result_binary", models.BinaryField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_items",
                        to="compute_management.simmateworker",
                    ),
                ),
            ],
            options={
                "db_table": "compute__work_items",
            },
            bases=(models.Model, simmate.database.core.archive.ArchiveMixin),
        ),
    ]
