###############
# NOTE: This file of dependencies is copied and modified from pyproject.toml
# It is meant only for dev and CI testing. You should refere to the toml file
# for official dependencies.
###############

# This env file was creating using...
# (1) anaconda docs
#	https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
# (2) grayskull to list deps
#	https://www.marcelotrevisani.com/grayskull
#
# To install this env, use `conda env create -f envs/conda/dev.yaml`

name: simmate_dev
channels:
    - conda-forge
dependencies:
    - ase >=3.22.1, <=3.22.1
    - black >=22.1.0, <=23.2.0
    - clease >1.0.3, <=1.0.6
    - cloudpickle >=2.1.0, <=2.2.0
    - coverage >=6.2, <7.0.6
    - dask-core >=2021.12.0, <2022.13.0
    - distributed >=2022.7.1, <2023.2.0
    - dj-database-url >=0.5.0, <1.3.0
    - django >=4.0.0, <4.1.6
    - django-allauth >=0.50.0, <=0.51.0
    - django-crispy-forms >=1.13.0, <=1.14.0
    - django-pandas >=0.6.6, <=0.6.6
    - django-filter >=21.1, <=22.1
    - django_unicorn >=0.50.0, <=0.50.0
    - djangorestframework >=3.13.1, <3.14.1
    - isort >=5.10.1, <=5.12.1
    - matminer >=0.7.6, <0.8.1
    - markdown >=3.4.1, <=3.4.1
    - mkdocs-material >=8.4.1, <9.0.10
    - mkdocstrings >=0.19.0, <=0.19.0
    - mkdocstrings-python >=0.7.1, <0.8.4
    - numpy >=1.22.0, <1.24.2
    - pandas >=1.3.5, <1.5.4
    - plotly >=5.4.0, <=5.14.0
    - pymatgen >=2022.1.9, <2023.1.21
    - pymatgen-analysis-diffusion >=2021.4.29, <=2022.7.21
    - pytest >=6.2.5, <=7.2.2
    - pytest-django >=4.5.2, <=4.5.2
    - python >=3.10
    - pytest-mock >=3.7.0, <3.10.1
    - pytest-xdist >=2.5.0, <=3.2.0
    - pyyaml >=6.0, <=6.0
    - requests >=2.28.1, <2.28.3
    - rich >=11.0, <=13.2.1
    - scikit-learn >=1.1.1, <1.2.2
    - toml >=0.10.2, <=0.10.2
    - typer >=0.6.0, <0.7.1
    # Recommended IDE for development -- We leave this as a separate install
    # because it's up to you and Spyder is a large package with many dependencies.
    # - spyder >=5.1.5
