###############
# NOTE: This file of dependencies is copied and modified from pyproject.toml
# It is meant only for dev and CI testing. You should refere to the toml file
# for official dependencies.
###############

# This env file was creating using...
# (1) anaconda docs
#	https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
# (2) grayskull to list deps
#	https://www.marcelotrevisani.com/grayskull
#
# To install this env, use `conda env create -f envs/conda/dev.yaml`

name: simmate_dev
channels:
    - conda-forge
dependencies:
    - ase >=3.22.1, <=3.23.0
    - black >=25.1.0, <26.0.0
    - clease >1.0.3, <=1.0.6
    - cloudpickle >=2.1.0, <=3.0.0
    - coverage >=6.2, <7.4.4
    - dask-core >=2023.6.1, <2024.4.3
    - distributed >=2023.6.1, <2024.4.3
    - django >=4.0.0, <4.2.8
    - django-allauth >=0.56.0, <=0.63.3
    - django-crispy-forms >=1.13.0, <=1.14.0
    #
    # A fork of django-unicorn was made, which we now use + its deps
    # - django_unicorn >=0.59.0, <=0.59.0
    - beautifulsoup4 >=4.8.0
    - orjson >=3.6.0
    - shortuuid >=1.0.1
    - cachetools >=4.1.1
    - decorator >=4.4.2
    #
    - django-simple-history >=3.3.0, <=3.3.0
    - djangorestframework >=3.13.1, <3.15.2
    - ipython >=8.22.2, <=8.29.0
    - isort >=5.10.1, <=5.12.1
    - matminer >=0.9.3, <=0.9.3
    - markdown >=3.4.1, <=3.5.1
    - mkdocs-material >=9.5.44, <9.6.0
    - mkdocstrings >=0.25.2, <=0.26.0
    - mkdocstrings-python >=1.10.9, <1.11.0
    - mkdocs-autorefs >=1.3.1, <1.4.0  # BUG-FIX
    - numpy >=1.22.0, <1.24.2
    - pandas >=2.0.0, <2.1.4
    - plotly >=5.4.0, <5.19.0
    - pymatgen >=2022.1.9, <2023.5.32
    - pymatgen-analysis-diffusion >=2021.4.29, <=2023.8.15
    - pytest >=6.2.5, <=7.3.2
    - pytest-django >=4.5.2, <=4.8.0
    - python >=3.10
    - pytest-mock >=3.7.0, <3.14.1
    - pytest-xdist >=2.5.0, <3.4.0
    - pyyaml >=6.0, <=6.0.1
    - rdkit >=2024.03.1, <=2024.03.1
    - requests >=2.28.1, <=2.32.3
    - rich >=11.0, <=13.5.2
    - scikit-learn >=1.1.1, <1.5.1
    - schedule >=1.2.0, <=1.2.0
    - toml >=0.10.2, <=0.10.2
    - typer >=0.6.0, <0.7.1
    - umap-learn >=0.5.5, <=0.5.5
    - xmltodict >=0.13.0, <=0.13.0
    # Recommended IDE for development -- We leave this as a separate install
    # because it's up to you and Spyder is a large package with many dependencies.
    # - spyder >=5.1.5
