name: simmate_dev
channels:
    - conda-forge
dependencies:
    - pytest >=6.2.5, <=7.3.2
    - pytest-django >=4.5.2, <=4.8.0
    - pytest-mock >=3.7.0, <3.14.1
    - pytest-xdist >=2.5.0, <3.4.0
    - black >=26.1.0, <27.0.0
    - coverage >=6.2, <7.4.4
    - isort =6.1.0
    - mkdocs-material >=9.5.44, <9.6.0
    - mkdocstrings >=0.25.2, <=0.26.0
    - mkdocstrings-python >=1.10.9, <1.11.0
    - mkdocs-autorefs >=1.3.1, <1.4.0  # BUG-FIX
