# Generated by Django 4.2.7 on 2026-02-10 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chembl", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chemblmolecule",
            name="acid_base_type",
        ),
        migrations.RemoveField(
            model_name="chemblmolecule",
            name="log_d_chemaxon",
        ),
        migrations.RemoveField(
            model_name="chemblmolecule",
            name="log_p_chemaxon",
        ),
        migrations.RemoveField(
            model_name="chemblmolecule",
            name="pka_acidic_max",
        ),
        migrations.RemoveField(
            model_name="chemblmolecule",
            name="pka_basic_max",
        ),
        migrations.RemoveField(
            model_name="chemblmolecule",
            name="rule_of_5_violations_lipinski",
        ),
    ]
