# Generated by Django 4.2.7 on 2026-02-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chembl", "0003_remove_chemblmolecule_acid_base_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemblmolecule",
            name="is_invalid_molecule",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
