# Generated by Django 4.2.7 on 2026-02-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chembl", "0004_chemblmolecule_is_invalid_molecule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chemblassayresult",
            name="source",
        ),
        migrations.RemoveField(
            model_name="chembldocument",
            name="source",
        ),
    ]
