# Generated by Django 5.2.11 on 2026-03-21 04:57

from django.db import migrations, models

import simmate.database.core.archive


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TableCount",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("table_name", models.CharField(max_length=255, unique=True)),
                ("row_count", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                models.Model,
                simmate.database.core.archive.ArchiveMixin,
            ),
        ),
    ]
