# Generated by Django 4.2.7 on 2024-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_explorer", "0002_alter_aflowprototype_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="aflowprototype",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aflowstructure",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codstructure",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jarvisstructure",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matprojstructure",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oqmdstructure",
            name="fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
