# Generated by Django 4.2.7 on 2025-03-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_explorer", "0002_alter_aflowprototype_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aflowstructure",
            name="spacegroup",
        ),
        migrations.RemoveField(
            model_name="codstructure",
            name="spacegroup",
        ),
        migrations.RemoveField(
            model_name="jarvisstructure",
            name="spacegroup",
        ),
        migrations.RemoveField(
            model_name="matprojstructure",
            name="spacegroup",
        ),
        migrations.RemoveField(
            model_name="oqmdstructure",
            name="spacegroup",
        ),
        migrations.DeleteModel(
            name="AflowPrototype",
        ),
        migrations.DeleteModel(
            name="AflowStructure",
        ),
        migrations.DeleteModel(
            name="CodStructure",
        ),
        migrations.DeleteModel(
            name="JarvisStructure",
        ),
        migrations.DeleteModel(
            name="MatprojStructure",
        ),
        migrations.DeleteModel(
            name="OqmdStructure",
        ),
    ]
