# Generated by Django 4.2.7 on 2024-10-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_explorer", "0003_aflowprototype_fingerprint_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aflowprototype",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
        migrations.RenameField(
            model_name="aflowstructure",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
        migrations.RenameField(
            model_name="codstructure",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
        migrations.RenameField(
            model_name="jarvisstructure",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
        migrations.RenameField(
            model_name="matprojstructure",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
        migrations.RenameField(
            model_name="oqmdstructure",
            old_name="fingerprint",
            new_name="fingerprint_crystalnn",
        ),
    ]
