# Generated by Django 4.2.7 on 2026-02-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="source",
        ),
    ]
