# Generated by Django 4.2.7 on 2026-01-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="token_balance",
            field=models.DecimalField(decimal_places=6, default=10000, max_digits=30),
        ),
    ]
