# Generated by Django 5.2.11 on 2026-03-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials_project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matprojstructure",
            name="updated_at_original",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="matprojstructure",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
