# Generated by Django 5.2.11 on 2026-03-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials_project", "0002_matprojstructure_updated_at_original_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matprojstructure",
            name="is_invalid_structure",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
