apiVersion: apps/v1
kind: Deployment
metadata:
  name: simmate-worker-deployment
  labels:
    app: simmate-worker
spec:
  selector:
    matchLabels:
      app: simmate-worker
  replicas: 0  # disabled for now
  template:
    metadata:
      labels:
        app: simmate-worker
        # bug-fix: https://stackoverflow.com/questions/46336852/
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: simmate-worker
          image: simmate/simmate-gunicorn:latest
          command: ["simmate", "compute", "start-worker"]
          env:
            {{- include "simmate.env_config" . | indent 12 }}
          volumeMounts:
            - mountPath: /simmate_workers
              name: simmate-worker-data
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
              ephemeral-storage: "1Gi"
            limits:
              memory: "4Gi"
              cpu: "1"
              ephemeral-storage: "2Gi"
      volumes:
        - name: simmate-worker-data
          persistentVolumeClaim:
            claimName: simmate-worker-data
