apiVersion: apps/v1
kind: Deployment
metadata:
  name: simmate-worker-deployment
  labels:
    app: simmate-worker
spec:
  selector:
    matchLabels:
      app: simmate-worker
  replicas: {{ .Values.simmate.workers.replicas }}
  template:
    metadata:
      labels:
        app: simmate-worker
        # bug-fix: https://stackoverflow.com/questions/46336852/
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: simmate-worker
          image: jacksund/simmate:dev
          command: ["simmate", "compute", "start-worker"]
          env:
            {{- include "simmate.env_config" . | indent 12 }}
          volumeMounts:
            - mountPath: /simmate_workers
              name: simmate-worker-data
          resources:
            requests:
              memory: {{ .Values.simmate.workers.resources.requests.memory }}
              cpu: {{ .Values.simmate.workers.resources.requests.cpu }}
              ephemeral-storage: {{ .Values.simmate.workers.resources.requests.ephemeral }}
            limits:
              memory: {{ .Values.simmate.workers.resources.limits.memory }}
              cpu: {{ .Values.simmate.workers.resources.limits.cpu }}
              ephemeral-storage: {{ .Values.simmate.workers.resources.limits.ephemeral }}
      volumes:
        - name: simmate-worker-data
          persistentVolumeClaim:
            claimName: simmate-worker-data
