
# This action builds a Docker image and then publishes it to DockerHub.
# See the guide at...
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Docker-Simmate

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Publish to DockerHub
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image-name: ["bader", "simmate", "quantum_espresso", "psi4"]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
      
      - name: Log in to Docker Hub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: |
            jacksund/${{ matrix.image-name }}
            ghcr.io/${{ github.repository }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294
        with:
          context: .
          file: ./envs/docker/${{ matrix.image-name }}.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
