name: publish-docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Docs to Github Pages
    steps:
    - name: Initial setup
      uses: actions/checkout@v3
    # --------
    # NOTE: this section is copied from lint-and-test.yml
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: uv sync --extra dev
    - name: Install Simmate
      run: uv pip install -e .
    # --------
    - name: Make documentation
      shell: bash -l {0}
      run: |
        uv run mkdocs gh-deploy --force
