name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # every Sunday at 23:00 UTC
    - cron: "0 23 * * 0"

jobs:

  lint-check:
    name: Code Quality Check
    runs-on: "ubuntu-latest"
    steps:
      - name: Initial setup
        uses: actions/checkout@v3
      - name: Black
        uses: psf/black@stable
      - name: iSort
        uses: isort/isort-action@master
      # TODO: djlint
      # TODO: maybe ruff for other file types

  python-test:
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]  # "macos-latest",
        python-version: ["3.11"]
    steps:
      - name: Initial setup
        uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --extra dev
      # --editable is needed because we need test files too
      - name: Install Simmate
        run: uv pip install -e .
      - name: Run default tests
        run: uv run pytest --durations=15

  docker-build:
    name: Docker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-name: ["bader", "simmate", "quantum_espresso", "psi4"]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Initial setup
        uses: actions/checkout@v3
      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./envs/docker/${{ matrix.image-name }}.dockerfile
          push: false
